### ISSUE TITLE
Chat messages are not logged to RCON (gamelog or getchat)

### ISSUE THREAD

**Issue by Zachar543** [Zachar543/ARK-Chat-Icons#2]
It appears something has changed (either with ARK or within the API) with how the send chat method logs to RCON. Currently, RCON's chat buffer is not being populated, so RCON commands that are used to retrieve chat no longer get any messages.

**Things to try:**
- [ ] Check if uncaught chat SendModes (e.g. MAX) could be used for RCON
- [ ] Check if we can emulate sending messages to RCON's chat buffer
- [ ] Check if there's something we can ignore that would let RCON's chat buffer receive chat

**Note:** ArkCrossServerChat has [the same issue](https://github.com/tsebring/ArkCrossServerChat/issues/5)

**Comment by Zachar543** [comment]
`getgamelog` is fixed in v1.02. No `getchat` yet, though.

**Comment by r2range** [comment]
how far are you with getchat? 

and i saw that you didnt use any hooks any reason for that?
